project:
  type: website
  output-dir: docs

website:
  title: "How to Create a Simple Machine Learning Model"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SimplyTim/blog_simple_ml_model

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



